### ISSUE TITLE
Create a basic animation system

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/astroships#7]
We need a spritesheet-based animation system that is simple to implement, and doesn't need to cover all cases.

- [x] Support only spritesheets that are uniform (same width/height for each sprite, with the sprite centered)
- [x] Spritesheets are expected to have no outer padding
- [x] Create an `Animation` with frames from the sheet, and duration of each frame
- [x] Animations must be time based

**Comment by avahe-kellenberger** [comment]
The system has been created, need to test actual images with @notchris  

- [x] We should be an AnimatedObject that uses the new system for testing

**Comment by notchris** [comment]
Initial tests looked good! I will report back on how animated sprites on moving objects look.

**Comment by avahe-kellenberger** [comment]
Closed via #9
